#!groovy

node {
    stage ("Get Latest Code") {
        checkout scm
    }

    stage ("Build Image") {
       docker.withTool("docker-latest"){
            def dockerfile = './dev-441/Dockerfile.ubuntu'
            def customImage = docker.build("von-image:py35-indy1.3.1-dev-441-ew", "-f ${dockerfile} ./dev-441/") 
        }
    }
}